// <auto-generated />
using System;
using Data_GestaoHospitalar.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data_GestaoHospitalar.Migrations
{
    [DbContext(typeof(GestaoHospitalarDbContext))]
    [Migration("20201219013835_AddMappingFluentApi-PacienteEstadoPaciente-All")]
    partial class AddMappingFluentApiPacienteEstadoPacienteAll
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain_GestaoHospitalar.Models.EstadoPaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("Descricao")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("EstadoPacientes");
                });

            modelBuilder.Entity("Domain_GestaoHospitalar.Models.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(11)")
                        .IsFixedLength(true)
                        .HasMaxLength(11);

                    b.Property<DateTime>("DataInternacao");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("EstadoPacienteId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Rg")
                        .HasColumnType("varchar(15)")
                        .IsFixedLength(true)
                        .HasMaxLength(15);

                    b.Property<DateTime>("RgDataEmissao");

                    b.Property<string>("RgOrgao")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Sexo");

                    b.Property<int>("TipoPaciente");

                    b.HasKey("Id");

                    b.HasIndex("EstadoPacienteId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Domain_GestaoHospitalar.Models.Paciente", b =>
                {
                    b.HasOne("Domain_GestaoHospitalar.Models.EstadoPaciente", "EstadoPaciente")
                        .WithMany("Paciente")
                        .HasForeignKey("EstadoPacienteId");
                });
#pragma warning restore 612, 618
        }
    }
}
